version: '3'
services:

  fluentd:
    image: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elastic/elasticsearch
    deploy:
      resources:
        limits:
          memory: 3500M
        reservations:
          memory: 2500M
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: elastic/kibana
    ports:
      - "5601:5601"
