version: '2'
services:
  opsmxApp:
    image: demoapp
    container_name: demo_log-server
    ports:
       - "9090:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: demoapp.access
